import { Movie } from "./movie-list.interface";

export interface ListForm {
  name:        string;
  description: string;
  language:    string;
  list_id:     number;
  listas:      any[];
}




// Generated by https://quicktype.io
export interface CreateListResponses{
  content: CreateListResponse[]


}

export interface CreateListResponse {
  status_code:    number;
  status_message: string;
  success:        boolean;
  list_id:        number;
  lista:          any[];
}




// Generated by https://quicktype.io

export interface AddToListResponse {
  success:        boolean;
  status_code:    number;
  status_message: string;
}


