import { Movie } from "./movie-list.interface";

export interface ListForm {
  name:        string;
  description: string;
  language:    string;
}




// Generated by https://quicktype.io
export interface CreateListResponses{
  content: CreateListResponse[]


}

export interface CreateListResponse {
  status_code:    number;
  status_message: string;
  success:        boolean;
  list_id:        number;
}




// Generated by https://quicktype.io

export interface AddToListResponse {
  success:        boolean;
  status_code:    number;
  status_message: string;
}

// Generated by https://quicktype.io

export interface PlaylistResponse {
  created_by:     string;
  description:    string;
  favorite_count: number;
  id:             string;
  items:          Item[];
  item_count:     number;
  iso_639_1:      string;
  name:           string;
  poster_path:    null;
}

export interface Item {
  adult:             boolean;
  backdrop_path:     string;
  genre_ids:         number[];
  id:                number;
  media_type:        string;
  original_language: string;
  original_title:    string;
  overview:          string;
  popularity:        number;
  poster_path:       string;
  release_date:      string;
  title:             string;
  video:             boolean;
  vote_average:      number;
  vote_count:        number;
}



